name: Web Development.. JavaScript.. PHP.. AWS.. IceHrm.. and Open Source
description: Web Development.. JavaScript.. PHP.. AWS.. IceHrm.. and Open Source
meta_description: "Full-Stack Web Developer blogging mostly about his open source projects and random intersting technical bits and pieces."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://thilinah.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'thilinahgithubio'

# Details for the RSS feed generator
url:            'http://thilinah.github.io'
author:         'Thilina Hasantha'
authorTwitter:  'thilina84'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
